[package]
name = "server"
version = "0.1.0"
authors = ["Ethan Ransom <derethanhausen@gmail.com>", "McKay Ransom <mckay.ransom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "*"
