name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Server
      run: cd server && go build

#    - name: Build Client
#      run: cd static && GOOS=js;GOARCH=wasm go build -o main.wasm

    - name: Test
      run: cd server && go test
